{
 "title": "Flight-Plan API Dashboard ",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "GET: /v1/flights",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"GET\",route=\"/v1/flights\"})"
    }
   ]
  },
  {
   "title": "GET: /v1/flights/:flight_id",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"GET\",route=\"/v1/flights/:flight_id\"})"
    }
   ]
  },
  {
   "title": "POST: /v1/flights",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"POST\",route=\"/v1/v1/flights\"})"
    }
   ]
  },
  {
   "title": "DELETE: /v1/flights",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{method=\"DELETE\",route=\"/v1/flights/:flight_id\"})"
    }
   ]
  }
 ]
}