{
 "title": "MongoDB dashboard",
 "time": { "from": "2019-01-07T13:08:43.750Z", "to": "2019-01-07T13:12:59.713Z" },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds"
    }
   ]
  },
  {
   "title": "Database Health",
   "type": "graph",
   "description": "1= Up\n0=Down",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mongodb_up" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "decmbytes", "label": "MB" }
   ],
   "targets": [
    { "expr": "mongodb_memory" }
   ]
  },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total[5m])"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_metrics_document_total[5m])"
    }
   ]
  }
 ]
}