apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: exporter-mongo-deployment
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: web
  spec:
   containers:
    - name: mongodb-exporter
      image: "gcr.io/mercedes-flight-service/exporter-mongodb-image:v3"
      ports:
       - containerPort: 9001 
